### ISSUE TITLE
[TODO] more usdLux support

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#101]
* [ ] Support more usdLux Prims
* [ ] Convert light infos in `tydra`
* [ ] Support usdLux in example viewer
  * We are better only focusing on it in raytraced renderer, since it is diffucult to implement various lights(e.g. Mesh light) in OpenGL/Vulkan renderer.
* [ ] Collection API in lights(light sets, shadow controls, etc) https://github.com/syoyo/tinyusdz/issues/108
