### ISSUE TITLE
Parse test failures in usd-wg/assets

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#135]
Branch: `dev`
Procedure:

```
$ cd <tinyusdz>/build
$ python ../tests/parse_usd/runner.py </path/to/usd-wg/assets>
# (run `test_tinyusdz` command for each USD files in the specified folder)
```

## Failure cases

```
/home/syoyo/work/usd/assets/full_assets/Teapot/Teapot_Materials.usd Failed
/home/syoyo/work/usd/assets/test_assets/TextureTransformTest/TextureTransformTest.usd Failed
/home/syoyo/work/usd/assets/test_assets/AlphaBlendModeTest/AlphaBlendModeTest.usd Failed
/home/syoyo/work/usd/assets/full_assets/StandardShaderBall/layers/environment.usda Failed
/home/syoyo/work/usd/assets/full_assets/StandardShaderBall/layers/shaderball.usda Failed
/home/syoyo/work/usd/assets/full_assets/McUsd/McUsd_10cm.usda Failed
/home/syoyo/work/usd/assets/full_assets/McUsd/McUsd.usda Failed
/home/syoyo/work/usd/assets/test_assets/schemaTests/usdGeom/meshes/normals_types/normalsTypes.usda Failed
/home/syoyo/work/usd/assets/test_assets/schemaTests/usdGeom/meshes/points_types/pointsTypes.usda Failed
/home/syoyo/work/usd/assets/test_assets/RelationshipEncapsulationTests/InternalReferenceTest.usda Failed
/home/syoyo/work/usd/assets/full_assets/ElephantWithMonochord/SoC-ElephantWithMonochord.usdc Failed
/home/syoyo/work/usd/assets/full_assets/UsdCookie/UsdCookie.usdz Failed
/home/syoyo/work/usd/assets/full_assets/McUsd/McUsd.usdz Failed
/home/syoyo/work/usd/assets/full_assets/McUsd/McUsd_10cm.usdz Failed
```

**Comment by syoyo** [comment]
## Reason of failures

Checked = fixed

* [ ] Nested variantSet `Teapot/Teapot_Materials.usd` https://github.com/syoyo/tinyusdz/issues/94
* [x] ReconstructMaterialBindingProperties():2168 PURPOSE must not have nested namespaces for 'mateirial:binding' `StandardShaderBall/layers/environment.usda`
* [x]  Comment in Stage meta `McUsd/McUsd_10cm.usda` https://github.com/syoyo/tinyusdz/issues/138
* [ ] type mismatch:  Parsing attribute `normals` failed. Error: Property type mismatch. normals expects type `normal3f[]` but defined as type `point3f[]` `normals_types/normalsTypes.usda`
  * Expected failure? 
* [x] Value block + metadata `RelationshipEncapsulationTests/InternalReferenceTest.usda`  https://github.com/syoyo/tinyusdz/issues/137
* [x] type mismatch: 0 Parsing attribute `inputs:st` failed. Error: Internal error. Invalid attribute value? get_value<texCoord2f> failed. in `ElephantWithMonochord/SoC-ElephantWithMonochord.usdc` fixed via https://github.com/syoyo/tinyusdz/commit/8a5491db31a28b469ec944eba0f157ca62aa0f33
* [ ] LoadUSDZFromMemory():545 Asset no[1] Image width too large `UsdCookie/UsdCookie.usdz`
  * Expected behavior? Texture width is 8192, and USDZ's limit is apparently set to 2048. https://forums.developer.apple.com/forums/thread/693867
* [ ] doubleSided attribute in Mesh is not qualified with `uniform`. `bool doubleSided = 1`  in `McUsd/McUsd_10cm.usda` `McUsd/McUsd_10cm.usdz`

**Comment by syoyo** [comment]
After fixing some issues in TinyUSDZ parser, now failure cases are reduced to 

```
/home/syoyo/work/usd/assets/full_assets/Teapot/Teapot_Materials.usd Failed
/home/syoyo/work/usd/assets/full_assets/StandardShaderBall/layers/shaderball.usda Failed
/home/syoyo/work/usd/assets/full_assets/McUsd/McUsd_10cm.usda Failed
/home/syoyo/work/usd/assets/full_assets/McUsd/McUsd.usda Failed
/home/syoyo/work/usd/assets/test_assets/schemaTests/usdGeom/meshes/normals_types/normalsTypes.usda Failed
/home/syoyo/work/usd/assets/test_assets/schemaTests/usdGeom/meshes/points_types/pointsTypes.usda Failed
/home/syoyo/work/usd/assets/test_assets/RelationshipEncapsulationTests/InternalReferenceTest.usda Failed
/home/syoyo/work/usd/assets/full_assets/ElephantWithMonochord/SoC-ElephantWithMonochord.usdc Failed
/home/syoyo/work/usd/assets/full_assets/UsdCookie/UsdCookie.usdz Failed
/home/syoyo/work/usd/assets/full_assets/McUsd/McUsd.usdz Failed
/home/syoyo/work/usd/assets/full_assets/McUsd/McUsd_10cm.usdz Failed
```

**Comment by tellypresence** [comment]
Do you also have status for model [`full_assets/CarbonFrameBike/CarbonFrameBike.usdz`](https://github.com/usd-wg/assets/blob/main/full_assets/CarbonFrameBike/CarbonFrameBike.usdz)?

**Comment by syoyo** [comment]
Failure cases with `dev` branch

```
/home/syoyo/work/usd/assets/full_assets/Teapot/Teapot_Materials.usd Failed
/home/syoyo/work/usd/assets/test_assets/TextureTransformTest/TextureTransformTest.usd Failed
/home/syoyo/work/usd/assets/full_assets/StandardShaderBall/layers/shaderball.usda Failed
/home/syoyo/work/usd/assets/full_assets/McUsd/McUsd_10cm.usda Failed
/home/syoyo/work/usd/assets/full_assets/McUsd/McUsd.usda Failed
/home/syoyo/work/usd/assets/test_assets/schemaTests/usdGeom/meshes/normals_types/normalsTypes.usda Failed
/home/syoyo/work/usd/assets/test_assets/schemaTests/usdGeom/meshes/points_types/pointsTypes.usda Failed
/home/syoyo/work/usd/assets/full_assets/McUsd/McUsd.usdz Failed
/home/syoyo/work/usd/assets/full_assets/McUsd/McUsd_10cm.usdz Failed
```

* test_assets/TextureTransformTest/TextureTransformTest.usd https://github.com/usd-wg/assets/issues/87
* ~~full_assets/Teapot/geo/FancyTeapot.usd Triangulation failed: Degenerated polygon found.~~ fixed via https://github.com/syoyo/tinyusdz/commit/b41e1ddb6837e53827d9c234c0ded59190fa6a0b
* Reason of issues for other scenes are discussed in https://github.com/syoyo/tinyusdz/issues/135#issuecomment-2041153203

**Comment by syoyo** [comment]
> Do you also have status for model [`full_assets/CarbonFrameBike/CarbonFrameBike.usdz`](https://github.com/usd-wg/assets/blob/main/full_assets/CarbonFrameBike/CarbonFrameBike.usdz)?

This issue is for parsing test(`tusdcat`). CarbonFrameBike.usdz passes with `tusdcat`.
FYI `tydra_to_renderscene` branch now does not report conversion error for `CarbonFrameBike.usdz`

**Comment by hybridherbst** [comment]
Good test list and documentation! 
cc @beersandrew, you might be interested in this as well
