### ISSUE TITLE
[TODO] Support wide color

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#142]
Wide color(wide gamut) support involves various things.

TinyUSDZ tries to support...

## Asset(Texture) load

* [x] sRGB DisplayP3 texture
* [ ] Linear DidplayP3 texture
* [x] OpenEXR texture(through TinyEXR)
* [x] DNG/TIFF Texture(through TinyDNG) 
* [ ] Texture with OCIO LUT profile?

## color space conversion

TinyUSDZ will provide at least linear-sRGB <-> linear-DisplayP3 conversion.

## Scene color space

Where shading/lighting occurs

* Linear sRGB (trationally known as linear color space)
* Linear DisplayP3
* ACEScg(AP1)

## Display(output)

This involves a viewer/renderer

* Android Vulkan wide gamut surface(DCI-P65, DisplayP3)  https://developer.android.com/training/wide-color-gamut
  * [ ] Add colorMode to `AndroidManifest.xml` in TinyUSDZ's Android example
  * [ ] Create DCI-P65 or Display-P3 surface/swapchain
* webgpu external texture DisplayP3

## Hardware

Wide-gamut supported display

* Recent iOS/Android device supports wide-gamut. Android chrome supports wide-gamut canvas display)
