### ISSUE TITLE
Support having multiple values in Attribute

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#154]
Currently TinyUSDZ's Attribute/Property implementation does not allow having multiple values(the first wins)

USD's Attribute can have multiple values(default value, timeSamples and connection)

https://lucascheller.github.io/VFX-UsdSurvivalGuide/core/elements/animation.html

we need to support a  syntax like this.
This would change TinyUSDZ's API

```
def Cube "Cube" (
)
{
    double size = 15
    double size.timeSamples = {
        1001: 1,
        1010: 10,
    }
   double size.connection = </path/to/value>
}
```

**Comment by syoyo** [comment]
## NOTE

timeSamples and connect seems not able to have attribute metadata

```
def Cube "Cube" (
)
{
    double size = 15 ( a = 3 ) # ok
    double size.timeSamples = {
        1001: 1,
        1010: 10,
    } ( a = 4) # fail
   double size.connection = </path/to/value> ( a = 5 ) # fail
}
```

**Comment by syoyo** [comment]
working branch: https://github.com/syoyo/tinyusdz/tree/multi-value-prop

**Comment by syoyo** [comment]
Added workaround to co-exist default value and timesamples in `rendermesh-refactor` branch: https://github.com/syoyo/tinyusdz/commit/bdedcc070b2acdf55c9ed0f041fa5f4a09db65d2

`[multi-value-prop](https://github.com/syoyo/tinyusdz/tree/multi-value-prop)` branch need to taking into account with this workaround when merging.

**Comment by syoyo** [comment]
## Work items

* [x] Support parsing multi value for Attribute in USDA parser  https://github.com/syoyo/tinyusdz/commit/0c147e535ad893d22c339834d269afc199cdbf74
* [x] Support parsing multi value for Attribute in USDC parser https://github.com/syoyo/tinyusdz/commit/0902c19bc2532defb3964e5641ff092cbaaff4d4
* [x] Support handling multi-value Attribute in PrimReconstruct
* [x] Support handling multi-value Attribute  in Tydra EvaluateAttribute

**Comment by syoyo** [comment]
Supported via https://github.com/syoyo/tinyusdz/commit/d7eb9da2da3f60b387094afaf7e49c41b7318836
