### ISSUE TITLE
[TODO] TinyUSDZLoader for Three.js

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#185]
https://github.com/lighttransport/tinyusdz/tree/dev/sandbox/threejs

## Background

Three.js has a USDZLoader, but it is written in pure JavaScript and cannot load full-spec of USDA and USDC(Binary).
TinyUSDZLoader, based on WASM-compiled TinyUSDZ, will provide more better USD loading functionality.
 
## NOTE

TinyUSDZ can be built with no-threading,  so no need of SharedArrayBuffer & Atomics support in the browser.

## Status

Work-in-progress

* [x] wasm compilation of TinyUSDZ
* [x] nodejs test loader
* [ ] Convert scene to Three.js 
* [ ] MaterialX support

**Comment by syoyo** [comment]
Texturing is now possible

https://github.com/mrdoob/three.js/issues/29169

**Comment by syoyo** [comment]
Wasm demo hosted on github pages!

https://lighttransport.github.io/tinyusdz/index.html

(Requires 8MB USDZ model download, so take a time to render)
