### ISSUE TITLE
[TODO] Support Composition Arcs

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#25]
## Status

Basic composition features are implemented(except for `specializes`)

Need verification to check if composition is working well or not

## Composition

* [x] subLayers
* [x] references
* [x] inherits
* [x] payloads(delayed load)
* [x] variants/variantSets
* [ ] specializers(not so much used? priority is low)

## Status

* [x] Preliminary support of parsing composition syntax in Ascii parser
* [x] Preliminary support of parsing composition info in Crate parser
* [x] Support `variantSet` stmt in Ascii parser.
* [x] Support SpecTypeVariant in Crate parser.
* [x] Load scene data as PrimSpec and Layer
* [x] Sematic reconstruction(composition) of Prims with Composition features
* [ ] Do test if composition is working expected
  * Verify Composition Strength ordering

## Crate(USDC) parser support

* [x] Parse `Payload` and `PayloadListOp` 
* [x] Parse `Referene` and `ReferenceListOp`
* [x] Parse `VariantSelectionMap` (`map<string, string>`)
* [x] Variant SdfSpecType
* [x] SpecTypeAttribute under Variant?

##  Limitation

Layer offsetting is not yet supported.

### subLayers

* [ ] LayerOffset(subLayerOffset) is not yet supported(ASCII)

### Reference

* [ ] LayerOffset is not yet supported(ASCII)
* [ ] customData is not yet supported(ASCII)

### Payload

* [ ] LayerOffset is not yet supported(ASCII)

**Comment by syoyo** [comment]
## Kitchen set

As of https://github.com/syoyo/tinyusdz/commit/187b50535cea69a20b47019ac45aa0a5cb60255b

* [x] Parse OK. Kitchen_set_instanced.usd also OK to parse.
* [x]  Reference, Payload
* [x] variants, inherits, over, ...
* [ ] Validate composition behavior is identical to pxrUSD

**Comment by syoyo** [comment]
## UsdSkel example

https://openusd.org/release/dl_usdskel_examples.html

* [x] Parse OK(in `tusdcat --flatten`
* [ ] Validate composition
