### ISSUE TITLE
[Task] Tydra RenderData

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#31]
# Goal

Convert USD data(usdGeom/usdShade/usdSkel) to Renderer(e.g. OpenGL/Vulkan, ray tracer) friendly data struct.
Currently focusing on rasterizer(meshes are all triangulated, vertex attributes can be drawn with single index buffer) and can display static mesh with texturing and PBR shading.

## Status for v0.8.0 release

* [x] Extract vertex indices and vertex points
* [x] Compute node transform https://github.com/syoyo/tinyusdz/blob/453b4a3b0e1c9a540ab1f9141dce53f184d22832/src/tydra/scene-access.hh#L264
* [x] Extract and setup UV coordinate
* [ ] Triangulate mesh
  * [x] Triangulate points, normals
  * [x] Triangulate uvs(primvars)
  * [ ] Triangulate other primvars 
* [ ] Extract and setup Material/Shader
  * [x] Evaluate Attribute value(Follow targetPath if the attribute is a Connection) to resolve shader graph connection
* [x] Extract and setup Texture image data
* [x] Partial TimeSample support 

## TODO, Furture work

* [ ] Skinning support
* [ ] Support TimeSample attributes of various Prims 
* [ ] Ray tracer friendly data structure
* [ ] More is T.B.W.

**Comment by syoyo** [comment]
Aggregated to https://github.com/syoyo/tinyusdz/issues/148
