### ISSUE TITLE
[TODO] Support sceneLibrary

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#36]
https://developer.apple.com/documentation/realitykit/scenelibrary

sceneLibrary feature would be rather easy to support than Variant in TinyUSDZ, and also be more intuitive.

* [x] `sceneName` Prim meta
* [x]  Support `sceneLibrary` in `kind` Prim meta. 
* [x] `over` Specifier keyword support
* [ ]  Tydra: Runtime active scene retrieval support(Something like SelectVariant)
  * [x] List up `sceneName`
  * [ ] Scene composition

**Comment by syoyo** [comment]
At least `sceneLibrary` `sceneName` and  `over` are now able to parse(both USDA and USDC) https://github.com/syoyo/tinyusdz/blob/dev/tests/usda/sceneLibrary-001.usda
