### ISSUE TITLE
[TODO] More CI build variant

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#38]
We need more CI build for portability check. For example...

* [ ] MinGW(gcc) build
* [ ] llvm-mingw(clang) build
* [ ] WASM/WASI build
* [ ] non-Ubuntu Linux build(e.g. Fedra, ArchLinux)
* [ ] clang-cl + msvcrt/ucrt build?(Need to have Windows SDK installed on build OS)
