### ISSUE TITLE
[TODO] Colorspace support

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#74]
This feature is related to MatrialX support

https://github.com/PixarAnimationStudios/USD/issues/1523

## Status

* [x] Parsing 'colorSpace' metadataum https://github.com/syoyo/tinyusdz/commit/8dce7bc170b466291f070884e53f8bee3c6e093a
* Colorspace support in Tydra
  * [x] Colorspace conversion
  * [x] Setup texture info with colorSpace https://github.com/syoyo/tinyusdz/commit/61fb00604985596a9e0c1c5bce138c4a8110b6c3
  * [ ]  OCIO lut support
 
## Mandatory.

This will be provided as a built-in colorspace

* `srgb_texture`
* `lin_rec709`
* `srgb_displayp3` https://www.wwdcnotes.com/notes/wwdc23/10086/

### Others

`ocio` colorspace will be provided only by SPI1D or SPI3D LUT through TinyColorIO https://github.com/syoyo/tinycolorio

## Physical unit

This relates to spectral color support in USD https://github.com/syoyo/tinyusdz/issues/57

* `irradiance`, `candela`(for texel value)

## Colorspace conversion implementation status

Implementation is located in Tydra and image-utils.cc  https://github.com/syoyo/tinyusdz/blob/dev/src/image-util.hh

* [x] sRGB <-> Linear
* [x] Rec709 <-> Linear
* [ ] OCIO
