### ISSUE TITLE
Extract variant information from USD and utilize it when compositing variants

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#84]
TinyUSDZ now supported references, payload and subLayers composition.

For command line composition of variant, we'll need to have variant/variantSet information applied to  USD.
Write a utility function(possibly in Tydra) to extra variant information and write it to JSON

## TODO

* [x] Extract variant info from USD Stage
* [ ] Extract variant info from USD Layer
  * [x] variant, variantSets
  * [ ] variantSet(variant Stmt)
* [ ] Save variant info to JSON
* [ ] Load variant info JSON and use it to select variantStmt

**Comment by syoyo** [comment]
Something like...

```
$ tusdcat --extract-variant input.usda 

{ "/xform0" : 
  { "variantSets" : ["rig"] ,
    "variants": {
      "rig": ["high", "low", "middle"],
    }
    "variantSelection": { "rig": "high" }
  }
}
```

```
$ tusdcat --flatten input.usda
# prints USD Prim with "high" selected for "rig" variant
```

edit JSON ...

```
{ "/xform0" : 
  { "variantSets" : ["rig"] ,
    "variants": {
      "rig": ["high", "low", "middle"],
    }
    "variantSelection": { "rig": "low" }
  }
}
```

```
$ tusdcat --flatten --variant input.json input.usda

# prints USD Prim with  "low" selected for "rig" variant
```

**Comment by syoyo** [comment]
Initial implementation of extracting variant.

https://github.com/syoyo/tinyusdz/commit/9061a87f3b666f8abbf4c08676dd0fb56050d340

```
#usda 1.0

def Xform "Implicits"
(
    append variantSets = ["shapeVariant"]
)
{
    variantSet "shapeVariant" = {
        "Capsule" {
            def Capsule "Pill"
            {
            }
        }
        "Cone" {
            def Cone "PartyHat"
            {
            }
        }
        "Cube" {
            def Cube "Box"
            {
            }
        }
        "Cylinder" {
            def Cylinder "Tube"
            {
            }
        }
        "Sphere" {
            def Sphere "Ball"
            {
            }
        }
    }
}
```

```
$ tusdcat --extract-variant filename.usda
```

```
{
    dictionary "/Implicits" = {
        dictionary variantSet = {
            string[] shapeVariant = ["Capsule", "Cone", "Cube", "Cylinder", "Sphere"]
        }
        string[] variantSets = ["shapeVariant"]
    }
}
```
