### ISSUE TITLE
[TODO] MaterialX support

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#86]
Working branch: `mtlx-2025`  https://github.com/syoyo/tinyusdz/tree/mtlx-2025

MaterialX spec: https://materialx.org/assets/MaterialX.v1.39.Spec.pdf
(version: 1.39)

Adding TinyUSDZ to load USD model in ASF MaterialXViewer https://github.com/lighttransport/materialx
(We can use this as a reference and for verification)

- [x] MaterialXConfigAPI
  - Inlined MaterialX Material description
- [ ] UsdMtlx Prim
- [ ] Visualization & rendering validation
  -  Plug tinyusdz + MaterialX into pbrlab? https://github.com/lighttransport/pbrlab
  - Use tinyusdz support fork of  ASF MaterialX https://github.com/lighttransport/materialx
  -
## Shading model support

- [ ] UsdPreviewSurface
- [ ] Autodesk Standard Surface
- [x] OpenPBR https://academysoftwarefoundation.github.io/OpenPBR/ https://github.com/syoyo/tinyusdz/issues/172

## TODO

- [x] MaterialX v1.39 support.

## Don't support

- Shaders in OSL, GLSL, etc
  - Support hardcoded shader only  

## Dataset for USD + MaterialX
 
- https://github.com/RogerDass/Usd-Mtlx-Example/

**Comment by syoyo** [comment]
Example syntax(?) of materialx

```
#usda 1.0

def "bora" 
(
   # Seems we need to specify </MaterialX> prim path
   references = @usd_preview_surface_default.mtlx@</MaterialX>
) {

}
```

```
$ usdcat --flatten materialx-001.usda 
#usda 1.0
(
    doc = """Generated from Composed Stage of root layer /mnt/data/work/tinyusdz/tests/usda/materialx-001.usda
"""
)

def "bora"
{
    def "Materials"
    {
        def Material "USD_Default"
        {
        }
    }
}
```

* Use `references` to load .mtlx
* Need to add `</MaterialX>` prim path(otherwise flatten fails)
* It looks Mtlx support in pxrUSD is not yet well supported(material/shader parameter not expanded)

**Comment by syoyo** [comment]
https://materialx.org/assets/MaterialX.v1.38.Supplement.pdf

## Texture nodes

* [ ] tiledimage(for texture mapping)
* [ ] triplanarprojection(for cube mapping?)
* [ ] ramp4

## Math nodes

* [ ] place2d
  * [ ] Mapping place2d to UsdTransform2d looses some infos(e.g. `pivot`) 
* [ ] safepower

## Adjustment nodes

* [ ] contrast
* [ ] range
* [ ] hsvadjust
* [ ] saturate

## Channel nodes

* [ ] extract
* [ ] separate2, separate3, separate4

**Comment by syoyo** [comment]
Working in `mtlx-2025` branch: https://github.com/lighttransport/tinyusdz/tree/mtlx-2025
