### ISSUE TITLE
[TODO] Fileformat handler(callback) API support

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinyusdz#87]
Provide Fileformat handler(callback) API to load custom dataset in user-side

Fileformat is basically determined by file extension.

## FileFormat API

- [x] Initial FileFormat API https://github.com/syoyo/tinyusdz/blob/9296b0c3d20592e7b4b69919cf79341182fa971b/src/asset-resolution.hh#L280

### Geometry, Material

- [x] USD: usd, usda, usdc, usdz
- [ ] MaterialX: mtlx https://github.com/syoyo/tinyusdz/issues/86
- [ ] Wavefront obj: .obj (usdObj)
- [ ] FBX? (usdFbx)

### Texture(image)

- [x] jpeg, png, bmp, tga and other 8bit LDR images: through stb_image
  - [x] 16bit PNG
- [x] oiio .tx(tiff), tiff, dng: tinydng 
- [x] EXR: tinyexr

### Audio

- [x] wav, mp3, flac: dr_wav
- [x] alac: alac lib

**Comment by syoyo** [comment]
Initial FileFormat API is now here:

https://github.com/syoyo/tinyusdz/blob/9296b0c3d20592e7b4b69919cf79341182fa971b/src/asset-resolution.hh#L280

And initial FileFormat example is at

https://github.com/syoyo/tinyusdz/tree/dev/examples/file_format
